# Generated by Django 6.0.5 on 2026-09-13 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='gravite',
            field=models.CharField(choices=[('P1', 'Urgence vitale'), ('P2', 'Urgence relative'), ('P3', 'Non urgent')], default='P2', help_text='Niveau de gravité évalué par le régulateur', max_length=2),
        ),
        migrations.AddField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de prise en charge'), ('prise_en_charge', 'Prise en charge par un régulateur'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='alerte',
            name='telephone_victime',
            field=models.CharField(blank=True, help_text='Numéro de la victime pour rappel', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='usager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to=settings.AUTH_USER_MODEL),
        ),
    ]
