# Generated by Django 5.0.6 on 2026-09-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alerte_gravite_statut_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo de l'incident", null=True, upload_to='alertes/'),
        ),
    ]
