# Generated by Django 6.0.5 on 2026-09-22 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alerte_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='ambulancier',
            field=models.ForeignKey(blank=True, help_text='Ambulancier assigné à ce véhicule', limit_choices_to={'role': 'equipe_intervention'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('maintenance', 'En maintenance'), ('en_panne', 'En panne')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('en_route', 'En route'), ('arrive', 'Arrivé sur les lieux'), ('prise_en_charge', 'Prise en charge'), ('transport', "Transport vers l'hôpital"), ('termine', 'Terminé'), ('en_panne', 'En panne')], default='en_route', max_length=20),
        ),
    ]
